name: Node.js CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'static/writing/posts.json'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm i
    - name: Execute prebuildJSON script
      run: node prebuild.js
    - name: Setup Git and Commit changes
      run: |
        git config --global user.name 'ekrenzin'
        git config --global user.email 'ean@eankrenzin.com'
        git checkout main
        git add static/writing/posts.json
        git commit -m "Update posts.json" || echo "No changes to commit"
        git push --set-upstream origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}